In [8]:
import numpy as np
from array import array
class Perceptron(object):
    """Implements a perceptron network"""
    def __init__(self, input_size, lr=1, epochs=10):
        self.W = np.zeros(input_size+1)
        # add one for bias
        self.epochs = epochs
        self.lr = lr
    
    def activation_fn(self, x):  
        return 1 if x >= 0 else 0
    
    def predict(self, x):
        x = np.insert(x, 0, 1)
        z = self.W.T.dot(x)
        a = self.activation_fn(z)
        return a
    
    def fit(self, X, d):
        for _ in range(self.epochs):
            for i in range(d.shape[0]):
                y = self.predict(X[i])
                e = d[i] - y
                self.W = self.W + self.lr * e * np.insert(X[i], 0, 1)
    

In [9]:
X = np.array([
        [0, 0],
        [0, 1],
        [1, 0],
        [1, 1]
     ])
X

array([[0, 0],
       [0, 1],
       [1, 0],
       [1, 1]])

In [10]:
d = np.array([0, 0, 0, 1])
d

array([0, 0, 0, 1])

In [11]:
perceptron = Perceptron(input_size=2)


In [12]:
perceptron.W

array([0., 0., 0.])

In [13]:
perceptron.fit(X, d)    

In [14]:
perceptron.W

array([-3.,  2.,  1.])

In [15]:
print(perceptron.W)

[-3.  2.  1.]


In [16]:
perceptron.predict(np.asarray([1,1]))

1

In [17]:
mp=Perceptron(5)
x=np.asarray([-10,-2,-30,-4,-50])
mp.predict(x)

1

In [ ]:
#def __init__ klasik sınıf tanımlaması. girdi sayısı, girdi boyutu ve ağırlık vektörünü dahil ediyoruz.
#aktivasyon fonksiyonu. girişin 0dan büyük olduğu durumlarda 1, diğer zamanlarda 0 olur.
#perception ve geri dönüş değerlerini hesaplayan fonksiyondur. Eğilim değerini giriş vektörüne ekliyoruz ve iç çarpım ve aktivasyon fonksiyonlarını kullanıyoruz. 